name: Deploy Shiny App to shinyapps.io

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("shiny", "rsconnect"))'

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
          SHINYAPPS_USERNAME: ${{ secrets.SHINYAPPS_USERNAME }}
        run: |
          Rscript -e "library(rsconnect); rsconnect::setAccountInfo(name = Sys.getenv('SHINYAPPS_USERNAME'), token = Sys.getenv('SHINYAPPS_TOKEN'), secret = Sys.getenv('SHINYAPPS_SECRET'))"
          Rscript -e "rsconnect::deployApp()"
