name: Deploy Shiny App to shinyapps.io

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-shiny:
    name: Deploy to shinyapps.io
    runs-on: ubuntu-latest
    env:
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      SHINYAPPS_USERNAME: ${{ secrets.SHINYAPPS_USERNAME }}
        
    steps:
       - name: 🛎️ Checkout repository
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
       - id: deploy
         name: 💎 Deploy to shinyapps.io
         uses: qwert666/shinyapps-actions@main
         env:
           SHINY_USERNAME: ${{ secrets.SHINYAPPS_USERNAME }}
           SHINY_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
           SHINY_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
           APP_NAME: 'SLV-Biotoxin-Validator-App'
           APP_DIR: ''
